all:clear compile run clean

compile: 1901042630_cse_344_hw1.c

	@gcc 1901042630_cse_344_hw1.c -c
	@gcc 1901042630_cse_344_hw1.o 

run:
	./a.out

clean:
	@rm -f *.o
	@rm -f *.out
	@rm -f *.txt
		
clear:	
	@clear
